language: python

python:
  - "3.7"

sudo: required

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov=save_commands/

after_success:
  - coveralls